# Inputs:
# - env.DOTNET_VERSION
name: test-dotnet-mutation

inputs:
  folder:
    description: Working directory of .NET solution
    required: true

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install Stryker
      shell: bash
      run: dotnet tool install -g dotnet-stryker

    - name: Mutation testing
      shell: bash
      run: dotnet stryker -O stryker
      working-directory: ${{ inputs.folder }}

    # TODO: Consider writing info to summary & badges.
    - name: Upload mutation test results
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.folder }}-mutation-test-results
        path: ${{ inputs.folder }}/stryker/reports/mutation-report.html
